# Generated by Django 3.0.2 on 2020-01-23 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20200123_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='questions_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
